/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Aluno
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }
    
    Calendar now = Calendar.getInstance();
    Date dataHora = new Date();
    
    String tipo;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbatend = new javax.swing.JLabel();
        lbtotem = new javax.swing.JLabel();
        lbsus = new javax.swing.JLabel();
        lbhora = new javax.swing.JLabel();
        lbpref = new javax.swing.JLabel();
        lbnorm = new javax.swing.JLabel();
        lbdata = new javax.swing.JLabel();
        lbsenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RETIRE SUA SENHA");

        lbatend.setText("jLabel3");

        lbtotem.setBorder(new javax.swing.border.MatteBorder(null));

        lbsus.setText("jLabel5");

        lbhora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbhora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbpref.setText("jLabel5");
        lbpref.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbprefMouseClicked(evt);
            }
        });

        lbnorm.setText("jLabel5");
        lbnorm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbnormMouseClicked(evt);
            }
        });

        lbdata.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbdata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbsenha.setBackground(new java.awt.Color(255, 255, 153));
        lbsenha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbsenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbsenha.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbhora, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(lbdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbtotem, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 82, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbpref, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(lbnorm, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbatend, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbsenha, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbsus, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbsus, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbatend, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbtotem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lbdata, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbhora, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 11, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbpref, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbnorm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    class dataHora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae)
        {
               Calendar now = Calendar.getInstance();
               lbhora.setText("Hora: " + String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }
    
      public void movimento()
    {
        
        Calendar now = Calendar.getInstance();
        //lbsenha.setText("Hora: " + String.format("%1$tH:%1$tM:%1$tS", now));
        lbsenha.setText("<html>"+"Hora: " + String.format("%1$tH:%1$tM:%1$tS", now)+"<br>" + tipo + "</html>");
        new Thread()
        {
            public void run()
            { 

               int y = 729;
               int x = 0;
               
                while(true)
                {
                    if( x < 123 )
                    {
                        x = x+1; 
                        lbsenha.setLocation(y , x);  
                    }
                    try
                    {
                        sleep(6);
                    }
                    catch (Exception e)
                    {
                    }
                }
            }
            
        }.start();
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ImageIcon imageIcon1 = new ImageIcon(new ImageIcon("src\\Img\\SUS.png").getImage().getScaledInstance(lbsus.getWidth(), lbsus.getHeight(), Image.SCALE_DEFAULT));
        lbsus.setIcon(imageIcon1); 
        ImageIcon imageIcon2 = new ImageIcon(new ImageIcon("src\\Img\\Atend_Pref.jpg").getImage().getScaledInstance(lbatend.getWidth(), lbatend.getHeight(), Image.SCALE_DEFAULT));
        lbatend.setIcon(imageIcon2);
        ImageIcon imageIcon4 = new ImageIcon(new ImageIcon("src\\Img\\normal1.png").getImage().getScaledInstance(lbnorm.getWidth(), lbnorm.getHeight(), Image.SCALE_DEFAULT));
        lbnorm.setIcon(imageIcon4);
        ImageIcon imageIcon5 = new ImageIcon(new ImageIcon("src\\Img\\pref.png").getImage().getScaledInstance(lbpref.getWidth(), lbpref.getHeight(), Image.SCALE_DEFAULT));
        lbpref.setIcon(imageIcon5);
        
        SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
        lbdata.setText("Data: " + dt.format(dataHora));
	
	Timer timer = new Timer(1000, new dataHora());
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void lbnormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbnormMouseClicked
        // TODO add your handling code here:
        movimento();
        tipo = "Atendimento preferencial";
    }//GEN-LAST:event_lbnormMouseClicked

    private void lbprefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbprefMouseClicked
        // TODO add your handling code here:
        movimento();
        tipo = "Atendimento normal";
    }//GEN-LAST:event_lbprefMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbatend;
    private javax.swing.JLabel lbdata;
    private javax.swing.JLabel lbhora;
    private javax.swing.JLabel lbnorm;
    private javax.swing.JLabel lbpref;
    private javax.swing.JLabel lbsenha;
    private javax.swing.JLabel lbsus;
    private javax.swing.JLabel lbtotem;
    // End of variables declaration//GEN-END:variables
}
